/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tests;

import cryptoconverter.implementations.PriceChangesPublisher;
import cryptoconverter.interfaces.IPriceChangeSubscriber;

/**
 *
 * @author gibra
 */
public class CryptoDisplay extends javax.swing.JFrame {

    private final PriceChangesPublisher publisher;

    public CryptoDisplay(PriceChangesPublisher publisher) {
        initComponents();
        this.publisher = publisher;
        this.addCriptoPriceSubscribers();
    }
    
    private void addCriptoPriceSubscribers(){
        this.publisher.subscribe(new IPriceChangeSubscriber() {
            @Override
            public void onPriceChanged(float price) {
                lblBitcoinPrice.setText(price + " USD");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBitcoin = new javax.swing.JLabel();
        lblBitcoinPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBitcoin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblBitcoin.setText("Bitcoin:");

        lblBitcoinPrice.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblBitcoinPrice.setForeground(new java.awt.Color(0, 0, 153));
        lblBitcoinPrice.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBitcoin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBitcoinPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBitcoin)
                    .addComponent(lblBitcoinPrice))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBitcoin;
    private javax.swing.JLabel lblBitcoinPrice;
    // End of variables declaration//GEN-END:variables
}
